image: node:10
clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Deploy to Heroku
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
